spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:kradnik}
spring.datasource.username=${POSTGRES_USER:kradnik}
spring.datasource.password=${POSTGRES_PASSWORD:kradnik}
