spring.application.name=kradnik

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:kradnik}
spring.datasource.username=${POSTGRES_USER:kradnik}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
